/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe. `db` tells you which backend is active (sqlite|postgres).
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/i/{guest_slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Invite */
        get: operations["get_invite_api_i__guest_slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/i/{guest_slug}/rsvp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Rsvp */
        post: operations["submit_rsvp_api_i__guest_slug__rsvp_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/i/{guest_slug}/wishes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Wishes
         * @description Approved guestbook messages for this wedding, newest first. The slug only
         *     serves to resolve (and gate access to) the tenant — every guest of the same
         *     wedding sees the same wall.
         */
        get: operations["list_wishes_api_i__guest_slug__wishes_get"];
        put?: never;
        /**
         * Create Wish
         * @description Leave a guestbook message. Tied to the resolved guest so the owner can
         *     moderate by person. Held UNAPPROVED on arrival — the couple must approve it
         *     from /admin before it shows on the public wall.
         */
        post: operations["create_wish_api_i__guest_slug__wishes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/landing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Landing
         * @description Copy for the public "no link" landing page (someone visiting the root with
         *     no personal link). Returns only the owner-editable `landing` block + theme.
         */
        get: operations["get_landing_api_landing_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_admin_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/guests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Guests */
        get: operations["list_guests_api_admin_guests_get"];
        put?: never;
        /** Create Guest */
        post: operations["create_guest_api_admin_guests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/guests/{guest_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Guest */
        delete: operations["delete_guest_api_admin_guests__guest_id__delete"];
        options?: never;
        head?: never;
        /** Update Guest */
        patch: operations["update_guest_api_admin_guests__guest_id__patch"];
        trace?: never;
    };
    "/api/admin/guests/{guest_id}/rsvp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Guest Rsvp
         * @description Owner override of a guest's RSVP (status + the whole party). Lets the couple
         *     record a response on a guest's behalf or correct one. `pending` removes the RSVP;
         *     `declined` keeps it but clears the party; `attending` sets the primary's own +
         *     invitee-scope `answers` and — when `companions` is given — the entire +1/child
         *     party with each person's own answers (wholesale replace, like the guest's own
         *     submit). Omitting `companions` leaves the companion party untouched.
         */
        put: operations["set_guest_rsvp_api_admin_guests__guest_id__rsvp_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/guests/bulk/rsvp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk Set Rsvp
         * @description Set the attendance status for many guests at once (the only bulk-editable
         *     field besides delete). Answers are left untouched; see `_set_rsvp_status`.
         */
        post: operations["bulk_set_rsvp_api_admin_guests_bulk_rsvp_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/guests/bulk/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk Delete Guests
         * @description Remove many guests at once (each cascades to its RSVP, like the single
         *     delete).
         */
        post: operations["bulk_delete_guests_api_admin_guests_bulk_delete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/companions/{companion_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Companion */
        delete: operations["delete_companion_api_admin_companions__companion_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Companion
         * @description Edit a single companion's name and/or its person-scope answers. `kind` stays
         *     as authored (adult vs child is structural and tier-gated). When `answers` is
         *     given it replaces this companion's answers wholesale, validated against the
         *     wedding's questions that apply to this person's kind.
         */
        patch: operations["update_companion_api_admin_companions__companion_id__patch"];
        trace?: never;
    };
    "/api/admin/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Questions */
        get: operations["list_questions_api_admin_questions_get"];
        put?: never;
        /** Create Question */
        post: operations["create_question_api_admin_questions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/questions/{question_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Question */
        delete: operations["delete_question_api_admin_questions__question_id__delete"];
        options?: never;
        head?: never;
        /** Update Question */
        patch: operations["update_question_api_admin_questions__question_id__patch"];
        trace?: never;
    };
    "/api/admin/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Content */
        get: operations["get_content_api_admin_content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Content
         * @description Partial edit of the invite's copy/details/theme. JSON sections deep-merge so
         *     the admin can PATCH a single block (e.g. just `content.cover`); `couple_names`
         *     is replaced. JSON columns are reassigned (not mutated) so SQLAlchemy flushes.
         */
        patch: operations["update_content_api_admin_content_patch"];
        trace?: never;
    };
    "/api/admin/story-arcs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Story Arcs */
        get: operations["list_story_arcs_api_admin_story_arcs_get"];
        put?: never;
        /** Create Story Arc */
        post: operations["create_story_arc_api_admin_story_arcs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/story-arcs/{arc_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Story Arc */
        delete: operations["delete_story_arc_api_admin_story_arcs__arc_id__delete"];
        options?: never;
        head?: never;
        /** Update Story Arc */
        patch: operations["update_story_arc_api_admin_story_arcs__arc_id__patch"];
        trace?: never;
    };
    "/api/admin/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Image
         * @description Accept a single image (multipart) and return a stored URL to drop into a
         *     story beat's `image`. Namespaced per wedding; dev → local disk, prod →
         *     Supabase Storage (see app/storage.py).
         */
        post: operations["upload_image_api_admin_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/responses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Responses */
        get: operations["list_responses_api_admin_responses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Summary */
        get: operations["summary_api_admin_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/summary/pivot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Summary Pivot
         * @description Configurable Overview pivot. `by` chooses the bars, `then` the stacked segments
         *     (one level). Optional scoping filters: `side` (a side label, e.g. "Alex"/"Sam"/
         *     "Unassigned") and `status` (e.g. "attending" for the Confirmed tab) restrict which
         *     guests are counted. `available_dims` is computed from the FULL list so the selector
         *     menu stays stable as you filter. Both an invalid/duplicate `then` (→ single bars)
         *     and an unavailable `by` (→ "side", else first available) fall back. Each cell
         *     carries BOTH measures (invitations + people) so the frontend renders any tab off
         *     one response.
         */
        get: operations["summary_pivot_api_admin_summary_pivot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/summary/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Summary Timeline
         * @description Cumulative RSVP replies bucketed by week (Monday-anchored), for the Overview's
         *     Trends chart. Counted by first reply (`responded_at`); `total_invitations` is the
         *     ceiling. Lazy-loaded by the UI only when the Trends panel is opened.
         */
        get: operations["summary_timeline_api_admin_summary_timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/wishes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Wishes */
        get: operations["list_wishes_api_admin_wishes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/wishes/{wish_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Wish */
        delete: operations["delete_wish_api_admin_wishes__wish_id__delete"];
        options?: never;
        head?: never;
        /** Moderate Wish */
        patch: operations["moderate_wish_api_admin_wishes__wish_id__patch"];
        trace?: never;
    };
    "/api/admin/export.xlsx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Xlsx
         * @description Split-row guest + RSVP workbook (one row per person), with dropdowns.
         */
        get: operations["export_xlsx_api_admin_export_xlsx_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/template.xlsx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Template Xlsx
         * @description A fillable template: the split-row header + a few example rows, with dropdowns.
         */
        get: operations["template_xlsx_api_admin_template_xlsx_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Guests
         * @description Upsert guests from a split-row XLSX (CSV also read). Dry-run by default
         *     (`commit=0`), returning a per-invitee preview of creates/updates/errors;
         *     `commit=1` applies.
         *
         *     Upsert key is the `Id` column (the guest UUID), scoped to this wedding — a blank
         *     Id creates a new guest, an Id that doesn't resolve is an error (the `Link` column
         *     is display-only and never matched on). The sheet's `Tier` is authoritative when
         *     set; a party with more companions than the (effective) tier allows is an error,
         *     never silently widened. Admin-defined question columns ARE written back: when a
         *     row sets `Attending`, its companions + answers replace the stored RSVP.
         */
        post: operations["import_guests_api_admin_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminMe */
        AdminMe: {
            /** Email */
            email: string;
            /** Via */
            via: string;
            /**
             * Wedding Id
             * Format: uuid
             */
            wedding_id: string;
            /** Wedding Slug */
            wedding_slug: string;
            /** Couple Names */
            couple_names: string;
        };
        /** AdminSummary */
        AdminSummary: {
            /** Total Guests */
            total_guests: number;
            /** Attending */
            attending: number;
            /** Declined */
            declined: number;
            /** Invited */
            invited: number;
            /** Pending */
            pending: number;
            /**
             * Invite Sent Count
             * @default 0
             */
            invite_sent_count: number;
            /** Head Count */
            head_count: number;
            /**
             * Invited People
             * @default 0
             */
            invited_people: number;
            /**
             * Pending People
             * @default 0
             */
            pending_people: number;
            /**
             * Declined People
             * @default 0
             */
            declined_people: number;
            /** Extra Adults */
            extra_adults: number;
            /** Extra Children */
            extra_children: number;
            /** Expected Head Count */
            expected_head_count: number;
            /**
             * @default {
             *       "by_side": {}
             *     }
             */
            capacity: components["schemas"]["CapacityConfig"];
            /**
             * Question Breakdowns
             * @default []
             */
            question_breakdowns: components["schemas"]["QuestionBreakdown"][];
            /**
             * By Side
             * @default []
             */
            by_side: components["schemas"]["GroupBreakdown"][];
            /**
             * By Tier
             * @default []
             */
            by_tier: components["schemas"]["GroupBreakdown"][];
            /**
             * Replies This Week
             * @default 0
             */
            replies_this_week: number;
            /**
             * Replies Last Week
             * @default 0
             */
            replies_last_week: number;
        };
        /** AnswerAdmin */
        AnswerAdmin: {
            /**
             * Question Id
             * Format: uuid
             */
            question_id: string;
            /** Prompt */
            prompt: string;
            /** Qtype */
            qtype: string;
            /** Value */
            value: Record<string, never>;
        };
        /** AnswerPublic */
        AnswerPublic: {
            /**
             * Question Id
             * Format: uuid
             */
            question_id: string;
            /** Value */
            value: Record<string, never>;
        };
        /** AnswerSubmit */
        AnswerSubmit: {
            /**
             * Question Id
             * Format: uuid
             */
            question_id: string;
            /** Value */
            value: Record<string, never>;
        };
        /** Body_import_guests_api_admin_import_post */
        Body_import_guests_api_admin_import_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** Body_upload_image_api_admin_upload_post */
        Body_upload_image_api_admin_upload_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /**
         * BulkGuestIds
         * @description A selection of this wedding's guests to act on in one shot. Ids that don't
         *     belong to the owner's wedding are silently ignored (the response `count` is the
         *     number actually affected), so a stray/foreign id can never touch another tenant.
         */
        BulkGuestIds: {
            /** Ids */
            ids: string[];
        };
        /** BulkResult */
        BulkResult: {
            /** Count */
            count: number;
        };
        /**
         * BulkRsvpUpdate
         * @description Set the attendance status for many guests at once (no answers — those stay
         *     as authored). `attending` keeps any existing party/answers; `declined` drops
         *     the party; `invited` marks invites as sent; `pending` clears the RSVP back to
         *     "no response".
         */
        BulkRsvpUpdate: {
            /** Ids */
            ids: string[];
            /** Status */
            status: string;
        };
        /**
         * Capabilities
         * @description Tier-derived limits, expressed so the UI never learns the tier name.
         *
         *     The RSVP form renders identical chrome for everyone and simply omits the
         *     companion fields when the caps are zero.
         */
        Capabilities: {
            /** Allow Plus One */
            allow_plus_one: boolean;
            /** Allow Kids */
            allow_kids: boolean;
            /** Max Adult Companions */
            max_adult_companions: number;
            /** Max Child Companions */
            max_child_companions: number;
            /**
             * Adults Multi
             * @default false
             */
            adults_multi: boolean;
        };
        /**
         * CapacityConfig
         * @description Owner-set guest capacity (people, not invitations), echoed from the wedding's
         *     `event_details.capacity`. `total` is the venue ceiling; `by_side` is an optional
         *     per-side ceiling keyed by the side label (e.g. "Alex"/"Sam"). Either can be
         *     unset — the capacity chart then just shows the used count without a ceiling.
         */
        CapacityConfig: {
            /** Total */
            total?: number | null;
            /**
             * By Side
             * @default {}
             */
            by_side: {
                [key: string]: number;
            };
        };
        /** CompanionAdmin */
        CompanionAdmin: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Name */
            name?: string | null;
            /**
             * Answers
             * @default []
             */
            answers: components["schemas"]["AnswerAdmin"][];
        };
        /** CompanionPublic */
        CompanionPublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Name */
            name?: string | null;
            /**
             * Answers
             * @default []
             */
            answers: components["schemas"]["AnswerPublic"][];
        };
        /** CompanionSubmit */
        CompanionSubmit: {
            /** Kind */
            kind: string;
            /** Name */
            name?: string | null;
            /**
             * Answers
             * @default []
             */
            answers: components["schemas"]["AnswerSubmit"][];
        };
        /**
         * CompanionUpdate
         * @description Owner edit of a single companion (the +1 or a child on an RSVP).
         *
         *     `kind` is structural (set by the invite/RSVP) and not editable here. `name` is
         *     left unchanged when omitted. `answers`, when provided, REPLACES this companion's
         *     person-scope answers wholesale (validated against the wedding's questions).
         */
        CompanionUpdate: {
            /** Name */
            name?: string | null;
            /** Answers */
            answers?: components["schemas"]["AnswerSubmit"][] | null;
        };
        /**
         * ContentAdmin
         * @description The whole editable surface of a wedding's invite (copy + details + theme).
         */
        ContentAdmin: {
            /** Couple Names */
            couple_names: string;
            /** Event Details */
            event_details: Record<string, never>;
            /** Content */
            content: Record<string, never>;
            /** Theme Tokens */
            theme_tokens?: Record<string, never> | null;
        };
        /**
         * ContentUpdate
         * @description Partial update. `event_details`, `content` and `theme_tokens` are
         *     deep-merged onto the stored JSON (so the admin can PATCH a single section);
         *     `couple_names` is replaced. Omitted fields are untouched.
         */
        ContentUpdate: {
            /** Couple Names */
            couple_names?: string | null;
            /** Event Details */
            event_details?: Record<string, never> | null;
            /** Content */
            content?: Record<string, never> | null;
            /** Theme Tokens */
            theme_tokens?: Record<string, never> | null;
        };
        /**
         * GroupBreakdown
         * @description One row of a grouped RSVP rollup — by side / batch / invite tier / relationship
         *     / group. Carries BOTH lenses so the same shape feeds the status bars and the
         *     headcount block: the four invitation-status counts (`pending`/`invited`/
         *     `attending`/`declined`, summing to `invitations`) and the people headcount
         *     (`head_count` confirmed vs `expected_head_count` estimated). `key` is a stable
         *     bucket id (`__unassigned__` for the no-value bucket); `label` is what's shown.
         *     `children` holds one optional level of sub-grouping (the pivot's "then by").
         */
        GroupBreakdown: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Invitations */
            invitations: number;
            /** Pending */
            pending: number;
            /** Invited */
            invited: number;
            /** Attending */
            attending: number;
            /** Declined */
            declined: number;
            /** Head Count */
            head_count: number;
            /**
             * Invited People
             * @default 0
             */
            invited_people: number;
            /** Expected Head Count */
            expected_head_count: number;
            /** People */
            people: number;
            /**
             * Children
             * @default []
             */
            children: components["schemas"]["GroupBreakdown"][];
        };
        /**
         * GuestAdmin
         * @description A guest row as the owner sees it — tier visible, with RSVP rollup.
         */
        GuestAdmin: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Invite Path */
            invite_path: string;
            /** Name */
            name: string;
            /** Greeting Name */
            greeting_name: string;
            /**
             * Party Members
             * @default []
             */
            party_members: components["schemas"]["PartyMember"][];
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
            /** Side */
            side?: string | null;
            /** Relationship */
            relationship?: string | null;
            /** Group Name */
            group_name?: string | null;
            /** Batch */
            batch?: string | null;
            /** Invite Tier */
            invite_tier: string;
            /** Invited */
            invited: boolean;
            /**
             * Invite Sent
             * @default false
             */
            invite_sent: boolean;
            /** Expected Party Size */
            expected_party_size?: number | null;
            /**
             * Story Arc Ids
             * @default []
             */
            story_arc_ids: string[];
            /** Rsvp Status */
            rsvp_status: string;
            /** Party Size */
            party_size: number;
            /** Notes */
            notes?: string | null;
            /** Responded At */
            responded_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
            /** First Source */
            first_source?: string | null;
            /** Last Source */
            last_source?: string | null;
            /** Last Actor */
            last_actor?: string | null;
            /**
             * Companions
             * @default []
             */
            companions: components["schemas"]["CompanionAdmin"][];
            /**
             * Answers
             * @default []
             */
            answers: components["schemas"]["AnswerAdmin"][];
        };
        /** GuestCreate */
        GuestCreate: {
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Invite Tier
             * @default solo
             */
            invite_tier: string;
            /** Greeting Name */
            greeting_name: string;
            /**
             * Party Members
             * @default []
             */
            party_members: components["schemas"]["PartyMember"][];
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
            /** Side */
            side?: string | null;
            /** Relationship */
            relationship?: string | null;
            /** Group Name */
            group_name?: string | null;
            /** Batch */
            batch?: string | null;
            /**
             * Invited
             * @default true
             */
            invited: boolean;
            /** Expected Party Size */
            expected_party_size?: number | null;
            /** Story Arc Ids */
            story_arc_ids?: string[] | null;
        };
        /**
         * GuestPublic
         * @description Only what the invite UI needs to greet the guest. No tier, no id leak.
         *
         *     `email`/`phone` are the guest's OWN previously-saved contacts, returned so the
         *     RSVP form can prefill them (editable). They come back MASKED (invite links get
         *     forwarded, so the holder of a link must not learn a saved contact); submitting
         *     the masked value back means "unchanged".
         */
        GuestPublic: {
            /** Name */
            name: string;
            /** First Name */
            first_name: string;
            /** Greeting Name */
            greeting_name: string;
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
            /**
             * Party Members
             * @default []
             */
            party_members: components["schemas"]["PartyMember"][];
        };
        /**
         * GuestRsvpUpdate
         * @description Owner edit of a guest's RSVP from /admin — set the attendance status and,
         *     when attending, the party answers (the primary person's own + invitee-scope).
         *
         *     `status`: `attending` / `declined` / `invited` / `pending`. `pending` clears any
         *     RSVP back to "no response, not yet contacted"; `invited` clears the RSVP but marks
         *     the guest as having been sent their invite. `declined` keeps the RSVP but drops
         *     companions + answers.
         *     `answers`, when provided (attending only), REPLACES the party answer list
         *     (companion_id NULL) wholesale; each must be a party question (invitee-scope, or
         *     person-scope applying to an adult — the primary counts as an adult).
         *     `companions`, when provided (attending only), REPLACES the whole companion party
         *     — each +1/child with its name and its own person-scope answers (e.g. a child's
         *     age, a +1's dietary). Validated against the tier's caps and each question's
         *     scope/applies_to server-side. Omit it to leave the companion party as-is (the
         *     single-companion endpoint still edits one at a time).
         */
        GuestRsvpUpdate: {
            /** Status */
            status: string;
            /** Notes */
            notes?: string | null;
            /** Answers */
            answers?: components["schemas"]["AnswerSubmit"][] | null;
            /** Companions */
            companions?: components["schemas"]["CompanionSubmit"][] | null;
        };
        /** GuestUpdate */
        GuestUpdate: {
            /** Name */
            name?: string | null;
            /** Invite Tier */
            invite_tier?: string | null;
            /** Greeting Name */
            greeting_name?: string | null;
            /** Party Members */
            party_members?: components["schemas"]["PartyMember"][] | null;
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
            /** Side */
            side?: string | null;
            /** Relationship */
            relationship?: string | null;
            /** Group Name */
            group_name?: string | null;
            /** Batch */
            batch?: string | null;
            /** Invited */
            invited?: boolean | null;
            /** Expected Party Size */
            expected_party_size?: number | null;
            /** Story Arc Ids */
            story_arc_ids?: string[] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportResult */
        ImportResult: {
            /** Committed */
            committed: boolean;
            /** Created */
            created: number;
            /** Updated */
            updated: number;
            /**
             * People Created
             * @default 0
             */
            people_created: number;
            /**
             * People Updated
             * @default 0
             */
            people_updated: number;
            /** Errors */
            errors: number;
            /**
             * Rows
             * @default []
             */
            rows: components["schemas"]["ImportRowResult"][];
        };
        /**
         * ImportRowResult
         * @description What happened to one invitee in an import (dry-run or committed).
         */
        ImportRowResult: {
            /** Row */
            row: number;
            /** Invitee */
            invitee: string;
            /** Action */
            action: string;
            /** Detail */
            detail?: string | null;
        };
        /**
         * InviteResponse
         * @description Everything the guest site needs to render the invitation for one link.
         */
        InviteResponse: {
            wedding: components["schemas"]["WeddingPublic"];
            guest: components["schemas"]["GuestPublic"];
            capabilities: components["schemas"]["Capabilities"];
            /** Questions */
            questions: components["schemas"]["QuestionPublic"][];
            /**
             * Story Arcs
             * @default []
             */
            story_arcs: components["schemas"]["StoryArcPublic"][];
            rsvp?: components["schemas"]["RsvpPublic"] | null;
        };
        /**
         * LandingResponse
         * @description Public "no link" landing page (the site root for someone without an invite).
         *
         *     Carries only the landing copy + theme tokens — no guest, no tier, no event
         *     internals beyond what the owner put in the landing block.
         */
        LandingResponse: {
            /** Couple Names */
            couple_names: string;
            /** Landing */
            landing: Record<string, never>;
            /** Theme Tokens */
            theme_tokens?: Record<string, never> | null;
        };
        /**
         * OptionCount
         * @description One bar in a question breakdown: an answer value and how many chose it.
         */
        OptionCount: {
            /** Label */
            label: string;
            /** Count */
            count: number;
        };
        /**
         * PartyMember
         * @description One pre-filled attendee (the +1 adult or a child). Just kind + name — the
         *     companion's own questions are answered at RSVP time, not pre-filled.
         */
        PartyMember: {
            /** Kind */
            kind: string;
            /**
             * Name
             * @default
             */
            name: string;
        };
        /**
         * PivotSummary
         * @description Interactive status pivot for the Overview (GET /summary/pivot). Invitation
         *     status + headcount grouped by `by`, optionally sub-grouped by `then`.
         *     `available_dims` lists the dimensions that actually split THIS guest list into
         *     ≥2 buckets (empty/single-value ones are omitted from the selector). `total` is
         *     the all-guests rollup for the footer/denominators.
         */
        PivotSummary: {
            /** By */
            by: string;
            /** Then */
            then?: string | null;
            /**
             * Available Dims
             * @default []
             */
            available_dims: string[];
            /**
             * Groups
             * @default []
             */
            groups: components["schemas"]["GroupBreakdown"][];
            total: components["schemas"]["GroupBreakdown"];
        };
        /** QuestionAdmin */
        QuestionAdmin: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Prompt */
            prompt: string;
            /** Qtype */
            qtype: string;
            /** Options */
            options: unknown[];
            /** Required */
            required: boolean;
            /** Scope */
            scope: string;
            /** Applies To */
            applies_to: string;
            /** Visibility */
            visibility: string;
            /** Visibility Ref */
            visibility_ref: unknown[];
            /** Sort Order */
            sort_order: number;
        };
        /**
         * QuestionBreakdown
         * @description Tally of a categorical question's answers across ATTENDING people/parties.
         *
         *     Generic over the question engine — every choice/multi_choice/yesno question is
         *     summarized the same way (this is how "how many Halal", "ages", etc. surface,
         *     without hardcoding any one question). `applicable` is how many people/parties
         *     could have answered (attending + matching the question's scope/applies_to);
         *     `answered` is how many actually did.
         */
        QuestionBreakdown: {
            /**
             * Question Id
             * Format: uuid
             */
            question_id: string;
            /** Prompt */
            prompt: string;
            /** Qtype */
            qtype: string;
            /** Scope */
            scope: string;
            /** Applies To */
            applies_to: string;
            /** Applicable */
            applicable: number;
            /** Answered */
            answered: number;
            /**
             * Counts
             * @default []
             */
            counts: components["schemas"]["OptionCount"][];
        };
        /** QuestionCreate */
        QuestionCreate: {
            /** Prompt */
            prompt: string;
            /** Qtype */
            qtype: string;
            /**
             * Options
             * @default []
             */
            options: string[];
            /**
             * Required
             * @default false
             */
            required: boolean;
            /**
             * Scope
             * @default invitee
             */
            scope: string;
            /**
             * Applies To
             * @default everyone
             */
            applies_to: string;
            /**
             * Visibility
             * @default all
             */
            visibility: string;
            /**
             * Visibility Ref
             * @default []
             */
            visibility_ref: string[];
            /**
             * Sort Order
             * @default 0
             */
            sort_order: number;
        };
        /** QuestionPublic */
        QuestionPublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Prompt */
            prompt: string;
            /** Qtype */
            qtype: string;
            /** Options */
            options: unknown[];
            /** Required */
            required: boolean;
            /** Scope */
            scope: string;
            /** Applies To */
            applies_to: string;
            /** Sort Order */
            sort_order: number;
        };
        /** QuestionUpdate */
        QuestionUpdate: {
            /** Prompt */
            prompt?: string | null;
            /** Qtype */
            qtype?: string | null;
            /** Options */
            options?: string[] | null;
            /** Required */
            required?: boolean | null;
            /** Scope */
            scope?: string | null;
            /** Applies To */
            applies_to?: string | null;
            /** Visibility */
            visibility?: string | null;
            /** Visibility Ref */
            visibility_ref?: string[] | null;
            /** Sort Order */
            sort_order?: number | null;
        };
        /** ResponseAdmin */
        ResponseAdmin: {
            /**
             * Guest Id
             * Format: uuid
             */
            guest_id: string;
            /** Guest Name */
            guest_name: string;
            /** Slug */
            slug: string;
            /** Attending */
            attending: boolean;
            /**
             * Responded At
             * Format: date-time
             */
            responded_at: string;
            /** Updated At */
            updated_at?: string | null;
            /** Last Source */
            last_source?: string | null;
            /** Last Actor */
            last_actor?: string | null;
            /** Notes */
            notes?: string | null;
            /**
             * Companions
             * @default []
             */
            companions: components["schemas"]["CompanionAdmin"][];
            /**
             * Answers
             * @default []
             */
            answers: components["schemas"]["AnswerAdmin"][];
        };
        /** RsvpConfirmation */
        RsvpConfirmation: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Attending */
            attending: boolean;
            /** Companion Count */
            companion_count: number;
        };
        /** RsvpPublic */
        RsvpPublic: {
            /** Attending */
            attending: boolean;
            /** Notes */
            notes?: string | null;
            /**
             * Companions
             * @default []
             */
            companions: components["schemas"]["CompanionPublic"][];
            /**
             * Answers
             * @default []
             */
            answers: components["schemas"]["AnswerPublic"][];
        };
        /**
         * RsvpSubmit
         * @description A guest's RSVP. Companions/answers are validated against the guest's tier
         *     and the wedding's visible questions server-side — the client cannot widen
         *     its own invite by posting extra companions.
         */
        RsvpSubmit: {
            /** Attending */
            attending: boolean;
            /** Notes */
            notes?: string | null;
            /** Name */
            name?: string | null;
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
            /**
             * Companions
             * @default []
             */
            companions: components["schemas"]["CompanionSubmit"][];
            /**
             * Answers
             * @default []
             */
            answers: components["schemas"]["AnswerSubmit"][];
        };
        /** StoryArcAdmin */
        StoryArcAdmin: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Visible */
            visible: boolean;
            /** Sort Order */
            sort_order: number;
            /** Content */
            content: Record<string, never>;
        };
        /** StoryArcCreate */
        StoryArcCreate: {
            /**
             * Title
             * @default Our story
             */
            title: string;
            /**
             * Visible
             * @default true
             */
            visible: boolean;
            /**
             * Sort Order
             * @default 0
             */
            sort_order: number;
            /** Content */
            content?: Record<string, never>;
        };
        /**
         * StoryArcPublic
         * @description A story arc as the guest sees it — content only.
         *
         *     The owner-facing `title`/`visible`/`sort_order` are deliberately omitted (an
         *     arc's internal label may hint at targeting, e.g. "Sam's family version").
         *     `id` is a stable, non-secret key for the carousel; the tier never appears.
         */
        StoryArcPublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Content */
            content: Record<string, never>;
        };
        /** StoryArcUpdate */
        StoryArcUpdate: {
            /** Title */
            title?: string | null;
            /** Visible */
            visible?: boolean | null;
            /** Sort Order */
            sort_order?: number | null;
            /** Content */
            content?: Record<string, never> | null;
        };
        /**
         * TimelinePoint
         * @description One weekly bucket of the RSVP timeline (Monday-anchored).
         */
        TimelinePoint: {
            /**
             * Week Start
             * Format: date
             */
            week_start: string;
            /** New */
            new: number;
            /** Cumulative */
            cumulative: number;
        };
        /**
         * TimelineSummary
         * @description Cumulative RSVP replies over time, for the admin Overview's Trends chart.
         *     Replies are counted by `responded_at` (the first reply), so edits don't inflate
         *     the curve. `total_invitations` is the ceiling line (all parties).
         */
        TimelineSummary: {
            /** Total Invitations */
            total_invitations: number;
            /** Total Replied */
            total_replied: number;
            /**
             * Points
             * @default []
             */
            points: components["schemas"]["TimelinePoint"][];
        };
        /** UploadResult */
        UploadResult: {
            /** Url */
            url: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WeddingPublic
         * @description The themeable, data-driven content for one wedding's invite.
         */
        WeddingPublic: {
            /** Couple Names */
            couple_names: string;
            /** Event Details */
            event_details: Record<string, never>;
            /** Content */
            content: Record<string, never>;
            /** Theme Tokens */
            theme_tokens?: Record<string, never> | null;
        };
        /**
         * WishAdmin
         * @description A guestbook message as the owner sees it — incl. moderation state.
         */
        WishAdmin: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Message */
            message: string;
            /** Approved */
            approved: boolean;
            /** Guest Name */
            guest_name?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * WishCreate
         * @description A guest leaving a message. Tied server-side to the resolved guest.
         */
        WishCreate: {
            /** Name */
            name: string;
            /** Message */
            message: string;
        };
        /** WishCreated */
        WishCreated: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Approved */
            approved: boolean;
        };
        /** WishModerate */
        WishModerate: {
            /** Approved */
            approved: boolean;
        };
        /**
         * WishPublic
         * @description A guestbook message as shown on the public wall (approved only).
         */
        WishPublic: {
            /** Name */
            name: string;
            /** Message */
            message: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_invite_api_i__guest_slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                guest_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_rsvp_api_i__guest_slug__rsvp_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                guest_slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RsvpSubmit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RsvpConfirmation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_wishes_api_i__guest_slug__wishes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                guest_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WishPublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_wish_api_i__guest_slug__wishes_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                guest_slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WishCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WishCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_landing_api_landing_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LandingResponse"];
                };
            };
        };
    };
    me_api_admin_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminMe"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_guests_api_admin_guests_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuestAdmin"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_guest_api_admin_guests_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GuestCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuestAdmin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_guest_api_admin_guests__guest_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                guest_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_guest_api_admin_guests__guest_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                guest_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GuestUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuestAdmin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_guest_rsvp_api_admin_guests__guest_id__rsvp_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                guest_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GuestRsvpUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuestAdmin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_set_rsvp_api_admin_guests_bulk_rsvp_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkRsvpUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_delete_guests_api_admin_guests_bulk_delete_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkGuestIds"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_companion_api_admin_companions__companion_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                companion_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_companion_api_admin_companions__companion_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                companion_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanionAdmin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_questions_api_admin_questions_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionAdmin"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_question_api_admin_questions_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionAdmin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_question_api_admin_questions__question_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                question_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_question_api_admin_questions__question_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                question_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionAdmin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_content_api_admin_content_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentAdmin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_content_api_admin_content_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentAdmin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_story_arcs_api_admin_story_arcs_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoryArcAdmin"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_story_arc_api_admin_story_arcs_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoryArcCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoryArcAdmin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_story_arc_api_admin_story_arcs__arc_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                arc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_story_arc_api_admin_story_arcs__arc_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                arc_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoryArcUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoryArcAdmin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_image_api_admin_upload_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_image_api_admin_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_responses_api_admin_responses_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseAdmin"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summary_api_admin_summary_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summary_pivot_api_admin_summary_pivot_get: {
        parameters: {
            query?: {
                by?: string;
                then?: string | null;
                side?: string | null;
                status?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PivotSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summary_timeline_api_admin_summary_timeline_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_wishes_api_admin_wishes_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WishAdmin"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_wish_api_admin_wishes__wish_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                wish_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    moderate_wish_api_admin_wishes__wish_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                wish_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WishModerate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WishAdmin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_xlsx_api_admin_export_xlsx_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    template_xlsx_api_admin_template_xlsx_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_guests_api_admin_import_post: {
        parameters: {
            query?: {
                commit?: boolean;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_guests_api_admin_import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
