"""initial schema

Revision ID: 9a4e0c2acead
Revises: 
Create Date: 2026-06-09 13:54:21.881151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a4e0c2acead'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weddings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=True),
    sa.Column('couple_names', sa.String(length=200), nullable=False),
    sa.Column('event_details', sa.JSON(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('theme_tokens', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weddings_owner_id'), 'weddings', ['owner_id'], unique=False)
    op.create_index(op.f('ix_weddings_slug'), 'weddings', ['slug'], unique=True)
    op.create_table('guests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('wedding_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('side', sa.String(length=40), nullable=True),
    sa.Column('relationship', sa.String(length=80), nullable=True),
    sa.Column('group_name', sa.String(length=120), nullable=True),
    sa.Column('batch', sa.String(length=40), nullable=True),
    sa.Column('invite_tier', sa.Enum('solo', 'plus_one', 'plus_family', name='invite_tier'), nullable=False),
    sa.Column('invited', sa.Boolean(), nullable=False),
    sa.Column('seed_meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['wedding_id'], ['weddings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guests_slug'), 'guests', ['slug'], unique=True)
    op.create_index(op.f('ix_guests_wedding_id'), 'guests', ['wedding_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('wedding_id', sa.Uuid(), nullable=False),
    sa.Column('prompt', sa.String(length=400), nullable=False),
    sa.Column('qtype', sa.Enum('choice', 'text', 'yesno', name='question_type'), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('visibility', sa.Enum('all', 'tier', 'guests', name='question_visibility'), nullable=False),
    sa.Column('visibility_ref', sa.JSON(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['wedding_id'], ['weddings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_wedding_id'), 'questions', ['wedding_id'], unique=False)
    op.create_table('rsvps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('wedding_id', sa.Uuid(), nullable=False),
    sa.Column('guest_id', sa.Uuid(), nullable=False),
    sa.Column('attending', sa.Boolean(), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dietary', sa.String(length=300), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wedding_id'], ['weddings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rsvps_guest_id'), 'rsvps', ['guest_id'], unique=True)
    op.create_index(op.f('ix_rsvps_wedding_id'), 'rsvps', ['wedding_id'], unique=False)
    op.create_table('wishes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('wedding_id', sa.Uuid(), nullable=False),
    sa.Column('guest_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wedding_id'], ['weddings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wishes_wedding_id'), 'wishes', ['wedding_id'], unique=False)
    op.create_table('answers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('wedding_id', sa.Uuid(), nullable=False),
    sa.Column('rsvp_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rsvp_id'], ['rsvps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wedding_id'], ['weddings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answers_question_id'), 'answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_answers_rsvp_id'), 'answers', ['rsvp_id'], unique=False)
    op.create_index(op.f('ix_answers_wedding_id'), 'answers', ['wedding_id'], unique=False)
    op.create_table('companions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('wedding_id', sa.Uuid(), nullable=False),
    sa.Column('rsvp_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('adult', 'child', name='companion_kind'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('dietary', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['rsvp_id'], ['rsvps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wedding_id'], ['weddings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companions_rsvp_id'), 'companions', ['rsvp_id'], unique=False)
    op.create_index(op.f('ix_companions_wedding_id'), 'companions', ['wedding_id'], unique=False)
    # ### end Alembic commands ###

    # --- Row Level Security backstop (multi-tenant isolation) ---
    # Enable RLS on every table with NO policies. The backend connects as the
    # `postgres` owner role, which bypasses RLS, so it retains full access. The
    # Supabase `anon` / `authenticated` roles (the public client SDK / PostgREST)
    # are non-owners and, with no policy granting access, are denied everything —
    # nothing tenant data leaks via the public API key. We intentionally do NOT
    # FORCE row level security, which would also apply it to the owner and lock
    # the backend out. App-level scoping (app/tenancy.py) is the primary guard;
    # this is the DB-level safety net.
    #
    # RLS is Postgres-only — skip it on SQLite so local dev can run this same
    # migration (the local DB is single-tenant and never internet-exposed).
    if op.get_bind().dialect.name == "postgresql":
        for _t in (
            "weddings", "guests", "rsvps", "companions", "questions", "answers", "wishes",
        ):
            op.execute(f'ALTER TABLE "{_t}" ENABLE ROW LEVEL SECURITY;')


def downgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        for _t in (
            "weddings", "guests", "rsvps", "companions", "questions", "answers", "wishes",
        ):
            op.execute(f'ALTER TABLE "{_t}" DISABLE ROW LEVEL SECURITY;')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companions_wedding_id'), table_name='companions')
    op.drop_index(op.f('ix_companions_rsvp_id'), table_name='companions')
    op.drop_table('companions')
    op.drop_index(op.f('ix_answers_wedding_id'), table_name='answers')
    op.drop_index(op.f('ix_answers_rsvp_id'), table_name='answers')
    op.drop_index(op.f('ix_answers_question_id'), table_name='answers')
    op.drop_table('answers')
    op.drop_index(op.f('ix_wishes_wedding_id'), table_name='wishes')
    op.drop_table('wishes')
    op.drop_index(op.f('ix_rsvps_wedding_id'), table_name='rsvps')
    op.drop_index(op.f('ix_rsvps_guest_id'), table_name='rsvps')
    op.drop_table('rsvps')
    op.drop_index(op.f('ix_questions_wedding_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_guests_wedding_id'), table_name='guests')
    op.drop_index(op.f('ix_guests_slug'), table_name='guests')
    op.drop_table('guests')
    op.drop_index(op.f('ix_weddings_slug'), table_name='weddings')
    op.drop_index(op.f('ix_weddings_owner_id'), table_name='weddings')
    op.drop_table('weddings')
    # ### end Alembic commands ###
